spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mydb
    username: myuser
    password: mypassword
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
