grpc:
  server:
    port: 9090
server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  datasource:
    url: ${POSTGRES-DB}
    username: ${POSTGRES-USERNAME}
    password: ${POSTGRES-PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
  kafka:
    bootstrap-servers: ${KAFKA-BOOTSTRAP-SERVERS}
services:
  vectorize-service-uri: ${VECTORIZE-SERVICE}
security:
  jwt:
    secret-key: ${JWT-SECRET:cbafda759821472b2a66d48a6f502c5a23ca19bea7b49970e82950fa001391d6}
    expiration-time: 864000000
  cors:
    frontendOrigin: ${FRONTEND-ORIGIN:*}
aws:
  ses:
    accessKey: ${AWS-SES-ACCESSKEY:a}
    secretKey: ${AWS-SES-SECRETKEY:a}
    configSet: ${AWS-SES-CONFIGSET:a}
    senderEmail: ${AWS-SES-SENDEREMAIL:a}