grpc:
  server:
    port: 9090
server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  datasource:
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
services:
  vectorize-service-uri: ${VECTORIZE_SERVICE}
security:
  jwt:
    secret-key: ${JWT_SECRET:cbafda759821472b2a66d48a6f502c5a23ca19bea7b49970e82950fa001391d6}
    expiration-time: 864000000
  cors:
    frontendOrigin: ${FRONTEND_ORIGIN:*}
aws:
  ses:
    accessKey: ${AWS_SES_ACCESSKEY:a}
    secretKey: ${AWS_SES_SECRETKEY:a}
    configSet: ${AWS_SES_CONFIGSET:a}
    senderEmail: ${AWS_SES_SENDEREMAIL:a}